### ISSUE TITLE
Zurich topojson rendering problems

### ISSUE THREAD

**Issue by adamgreenhall** [swissnexSF/Urban-Data-Challenge#5]
I'm having trouble rendering the Zurich routes as svg paths using topojson. The rendering of the SF and Geneva routes works just fine. Also, rendering the Zurich stops data works just fine. Not sure if this is related, but I tried to regenerate the topojson from the geojson using the rakefile and got some topojson maximum quantization errors. 

Any Ideas @herrstucki?

**Comment by adamgreenhall** [comment]
Here's a screenshot of the problem. The route paths are the black lines.
![zurich](https://f.cloud.github.com/assets/704919/289735/bacd8540-92c2-11e2-8864-3b06c1a036db.png)

**Comment by biovisualize** [comment]
I surely don't want to drive in Zurich ;)

![zurich](https://f.cloud.github.com/assets/824534/293161/993f3fb6-9346-11e2-88ba-bfeaa54c9a26.jpg)

This is from the geojson. Is it WGS84 or am I also missing something?

**Comment by poezn** [comment]
The routes Shapefile had the projection set to CH1903 (apparently the standard projection for Switzerland). Since both the GeoJSON and TopoJSON were generated from the shapefile the projection just got carried on. Should be fixed with commit 84351c251236ada63da2d2645627392d0ff9290a

**Comment by adamgreenhall** [comment]
@biovisualize - thanks for confirming the issue - I though I was might just be missing some topojson magic.
@poezn - thanks for fixing it! Zurich looks great now.
